{sp} +
{sp} +

***

[[integrations-beats]]
== Integrations

=== Elasticsearch: ApexBeats
*@since 0.7*

Elasticsearch can be extended using https://www.elastic.co/guide/en/beats/libbeat/current/community-beats.html[CommunityBeats], a range of service integrations that provide data to the Elasticsearch stack.

APEX provides an integration called https://github.com/verticle-io/apexbeats[Apexbeats]. This beats implementation is deployed with an APEX Collector Agent.
It is a bridgehead for directly importing data generated by APEX into Elasticsearch.

Apexbeats is also open sourced on https://github.com/verticle-io/apexbeats[Github].

==== Installing and Running ApexBeats

===== Prerequisites

* Golang 1.7
* `GOPATH` set
* project location at `${GOPATH}/github.com/verticle-io`

===== Build
Clone https://github.com/verticle-io/apexbeats to your project location dir.

[source, bash]
----
# fetch dependencies
make setup

# compile it with
make
----

===== Configure
Now alter the configuration file `apexbeat.yml` to your needs and set the http port properly.

===== Run

ApexBeats is now ready to start.

[source, bash]
----
# run it with
./apexbeat -c apexbeat.yml -e -d "*"
----



NOTE: You can find a more detailed setup guide on the Github https://github.com/verticle-io/apexbeats[README].

==== Connecting the APEX Collector to ApexBeats

At this point we assume your APEX Collector has already been set up. If not checkout the <<Quickstart>> chapter.

To make the APEX Collector talk to ApexBeats is simple. Alter your Collector configuration like this:

[source, bash]
----
# set the mode to beats
verticle.apex.service.method=beats
# set the service URL to point to ApexBeats
verticle.apex.service.uri=http://127.0.0.1:9005
----

Now restart the JVM with the Collector attached and view the logs.

NOTE: Both the Collector and the ApexBeats can be either deployed to the same or different hosts.
When deployed tp different hosts make sure ApexBeats is not blocked by firewall.
